# Generated by Django 2.2.28 on 2025-09-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Us',
            fields=[
                ('id', models.IntegerField(verbose_name='ID')),
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='用户名')),
                ('password', models.IntegerField(verbose_name='密码')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息管理',
                'db_table': 'user',
            },
        ),
    ]
