# Generated by Django 2.2.28 on 2025-09-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MQTTMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255, verbose_name='主题')),
                ('payload', models.TextField(verbose_name='消息内容')),
                ('qos', models.IntegerField(default=0, verbose_name='服务质量')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='接收时间')),
            ],
            options={
                'verbose_name': 'MQTT消息',
                'verbose_name_plural': 'MQTT消息管理',
                'db_table': 'mqtt_messages',
                'ordering': ['-timestamp'],
            },
        ),
    ]
