# Generated by Django 2.2.28 on 2025-09-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_mqttmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Da',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField(max_length=6, verbose_name='温度')),
                ('light', models.FloatField(max_length=6, verbose_name='光照')),
                ('do', models.FloatField(max_length=6, verbose_name='溶解氧')),
                ('tds', models.FloatField(max_length=6, verbose_name='TDS')),
                ('time', models.CharField(max_length=20, verbose_name='时间')),
            ],
            options={
                'verbose_name': '数据信息',
                'verbose_name_plural': '数据信息管理',
                'db_table': 'datas',
            },
        ),
    ]
